"""CPU-only causal-model tests; no GPU evidence is generated by these fixtures."""
from pathlib import Path
import csv
import json
import math
import os
import shutil
import struct
import sys
import tempfile
import unittest
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'python'))
from sdf_joint_reference import (initial_joint, causal_step, simulate_joint, search_path,
    joint_payload_bytes, verify_export, WORD_HEADER, SEARCH_HEADER)
from sdf_atlas import default_config, write_atlas
from sdf_lineage_reference import BRANCH, DIAGNOSTIC
from sdf_nor_reference import table_output
from universal_reference import parse_program, read_program, pack_state
from reference import observe, bank


def save_json(path, value):
    path.write_text(json.dumps(value), encoding='utf-8')


def write_csv(path, fields, values):
    with path.open('w', encoding='utf-8', newline='') as stream:
        writer = csv.DictWriter(stream, fieldnames=fields)
        writer.writeheader()
        writer.writerows(values)


def fixture(directory, *, injection='none', layout='linear'):
    """Hand-specified one-step q0→halt q1, symbol0→1, one angular winding.

    Two IDs collide at (2,0); every JK toggles. This does not call the joint
    simulator, native compiler, verifier or GPU. Device identity is synthetic.
    """
    from sdf_nor_reference import GATE_HEADER
    program = 'atomos-universal 1\nstates 2\nalphabet 2\nstart 0 0\nhalt 1\nrule 0 0 1 1 S\nrule 0 1 1 1 S\n'
    (directory / 'program.atomos').write_text(program, encoding='utf-8')
    write_atlas(default_config('nor_sites', 3, 64), directory / 'operators.atlas')
    circuit = dict(schema='atomOS-sdf-nor-circuit-v1', states=2, alphabet=2, control_bits=1,
        symbol_bits=1, input_count=3, gates=[[0, 0]], outputs=[3, 3, 2, 2, 3, 0, 3])
    save_json(directory / 'circuit.json', circuit)
    fault, applied = injection != 'none', injection != 'gate'
    before_leaf = [dict(id=1, row=0, angle=0)]
    after_leaf = [dict(id=i, row=2, angle=0) for i in (2, 3)] if applied else before_leaf
    original = pack_state({}, origin=-1, cells=35, alphabet=2, original_words=[0xa5a5a5a5] * 2)
    after_tape = pack_state({0: 1} if applied else {}, origin=-1, cells=35, alphabet=2, original_words=original)
    before_word, before_q = [1, 0, 0, 0, 0, 0], [0] * 6
    after_word = [int(injection == 'word'), 0, 0, 0, 1, 0] if applied else before_word
    after_q = [1] * 6 if applied else before_q

    def write_snapshot(path, prefix, tape, leaves, words, q):
        (path / (prefix + '_tape.u32le')).write_bytes(struct.pack('<II', *tape))
        write_csv(path / (prefix + '_frontier.csv'), ['id', 'row', 'angle'], leaves)
        write_csv(path / (prefix + '_words.csv'), ['lane', 'word', 'q'],
            [dict(lane=i, word=w, q=q[i]) for i, w in enumerate(words)])

    write_snapshot(directory, 'before', original, before_leaf, before_word, before_q)
    write_snapshot(directory, 'candidate', after_tape, after_leaf, after_word, after_q)
    write_snapshot(directory, 'committed', *( (original, before_leaf, before_word, before_q)
                   if fault else (after_tape, after_leaf, after_word, after_q)))
    step = directory / 'step_0'
    step.mkdir()
    write_snapshot(step, 'before', original, before_leaf, before_word, before_q)
    write_snapshot(step, 'candidate', after_tape, after_leaf, after_word, after_q)
    output = int(applied)
    decoded = dict(next=output, write=output, move=0, defined=output, halt_current=0, halt_after=output)
    transition = dict(control_before=0, control_after=1, read=0, write=1, head_before=0, head_after=0, move=0) if applied else None
    save_json(step / 'step.json', dict(evaluation=0, step=0, applied=applied,
        status='halted' if applied else 'missing_rule', machine=dict(control=0, head=0), read=0,
        decoded=decoded, transition=transition, before_count=1, after_count=len(after_leaf),
        children=2 if applied else 0, phi_steps=64 if applied else 0, searches=4 if applied else 0,
        time_before=0, time_candidate=.125 if applied else 0))
    write_csv(step / 'gate_trace.csv', GATE_HEADER,
        [dict(evaluation=0, gate=0, a=0, b=0, output=output, texel=16 if layout == 'linear' else 4,
              parity=1, asa=7, na=7, boundary=6, fringe=7)])
    children = [dict(id=2+b, parent=1, branch=b, row=2, angle=0, parity=1,
        delta_phi=(1 if b == 0 else -1) * math.tau, live=1, diagnostic_status=0, admitted=1)
        for b in range(2)] if applied else []
    write_csv(step / 'branches.csv', BRANCH, children)
    diagnostics = []
    for child in children:
        sample = dict(dr=0.0, dp=child['delta_phi'], alpha=0.0, interval=.125,
                      profile=1, axis_known=1, frame_known=1, increment_known=1)
        observation = observe(sample)
        diagnostic = dict(id=child['id'], delta_rho=0.0, delta_phi=sample['dp'], alpha=0.0, interval=.125, **observation)
        for i, probe in enumerate(bank(sample, observation)):
            diagnostic.update({f'check{i}_{key}': value for key, value in probe.items()})
        diagnostics.append(diagnostic)
    write_csv(step / 'diagnostics.csv', DIAGNOSTIC, diagnostics)
    records = []
    for lane in range(6) if applied else []:
        row, word = divmod(lane, 2)
        texel = row * 8 + word if layout == 'linear' else ((row & 1) | ((row & 2) << 1) | (word << 1))
        value = int(lane == 4)
        records.append(dict(lane=lane, emitted=value, q_before=0, texel=texel,
            asa_mask=7, na_mask=7, boundary_mask=6, fringe_mask=7, produced=value,
            asa=value, na=value, hits=0, output=after_word[lane], q_after=1, blend=0, blend_known=0))
    write_csv(step / 'words.csv', WORD_HEADER, records)
    searches = []
    for index, (key, found, path) in enumerate(((2, 0, [1, 0]), (3, 1, [1]),
                    (0, (1 << 32) - 1, [1, 0]), ((1 << 64) - 1, (1 << 32) - 1, [1]))) if applied else []:
        searches.append(dict(index=index, key=key, found=found, visits=len(path), overflow=0,
            **{f'path{i}': path[i] if i < len(path) else (1 << 32) - 1 for i in range(33)}))
    write_csv(step / 'search.csv', SEARCH_HEADER, searches)
    summary = dict(schema='atomOS-sdf-joint-v1', profile='new-finite-NOR-controlled-Klein-lineage-v1',
        topology='klein_m1_angular_twist', operator_source='loaded-SDF-predicate-atlas', runtime_rule_table=False,
        controller_coupling='phi_steps = base_phi_steps * (1 + decoded.write)',
        empty_frontier_policy='continue controller and every word JK update',
        search_organization='sorted-array binary search / implicit balanced BST', child_ids='2*positive_parent_id+branch',
        collision_policy='admit every child ID whose packed cell survives',
        commit_scope='all verified earlier joint steps as one candidate prefix; verification failure restores initial state',
        kernel_launches=1, active_threads=1, block_threads=32,
        tape_addressing='nonaliasing signed logical addresses separate from immutable operator texture',
        rows=3, angles=64, words=2, padded_rows=8, padded_words=8,
        atlas_file_bytes=112, atlas_texture_bytes=1024, control_bits=1, symbol_bits=1, circuit_gates=1,
        circuit_wires=4, origin=-1, cells=35, steps_budget=1, max_frontier=4, base_phi_steps=32,
        tail_fill=0xa5a5a5a5, j=1, k=1, q_initial=0, layout=layout, injection=injection,
        diagnostic_profile='directed', interval=.125,
        seed=dict(id=1, live=1, lifted_row=0, lifted_angle=0, row=0, angle=0, parity=0),
        candidate_verified=not fault, run_completed=not fault, status='rejected_verification' if fault else 'passed',
        program_stop='halted' if applied else 'missing_rule', reference_stop='halted',
        executed_steps=int(applied), evaluations=1, committed_steps=int(not fault),
        before_frontier_count=1, candidate_frontier_count=len(after_leaf), committed_frontier_count=1 if fault else 2,
        before=dict(control=0, head=0), candidate=dict(control=int(applied), head=0),
        committed=dict(control=int(not fault), head=0), time_before=0,
        time_candidate=.125 if applied else 0, time_committed=0 if fault else .125,
        verification=dict(passed=not fault, checks=1, gates_checked=1, words_checked=6, children_checked=2, searches_checked=4),
        warm_checksum=[0] * 4, reread_checksum=[0] * 4, sm_before=0, sm_after=0,
        texture_reads=dict(warm=64, gates=1, filter=6 if applied else 0, reread=64, total=135 if applied else 129),
        abi=dict(gate=8, gate_trace=36, step_trace=120, result_trace=80, word_trace=60, search_trace=152,
                 leaf=16, branch=48, diagnostic=136, state=8),
        device_payload_bytes=3576, host_geometry_bytes=3600, memory_budget_bytes=256 << 20, reserve_bytes=512 << 20,
        device=dict(name='CPU synthetic fixture; not GPU evidence', free_bytes_at_start=1 << 30,
            total_bytes=2 << 30, max_texture_1d_linear=1 << 20, runtime=0, driver=0, cc_major=0, cc_minor=0),
        registers_per_thread=0, local_bytes_per_thread=0, static_shared_bytes=0, kernel_ms=0)
    save_json(directory / 'summary.json', summary)
    (directory / ('REJECTED' if fault else 'COMMITTED')).write_text('CPU-only fixture\n', encoding='utf-8')
    return summary


def nor_atlas():
    return dict(rows=8, angles=64, words_per_row=2,
                planes={key: np.full((8, 2), value, dtype=np.uint32)
                        for key, value in zip(('asa', 'na', 'boundary', 'fringe'), (7, 7, 6, 7))})


class SdfJointReferenceTests(unittest.TestCase):
    @unittest.skipUnless(os.environ.get('ATOMOS_JOINT_FIXTURE'), 'optional retained actual export not configured')
    def test_retained_actual_export_detects_mutated_evidence(self):
        source = Path(os.environ['ATOMOS_JOINT_FIXTURE']).resolve()
        self.assertEqual(verify_export(source)['status'], 'passed')
        for target_name, key in (('step_0/gate_trace.csv', 'output'),
                                 ('step_0/branches.csv', 'row'),
                                 ('step_0/diagnostics.csv', 'status'),
                                 ('step_0/words.csv', 'q_after'),
                                 ('step_0/search.csv', 'path0')):
            with self.subTest(target=target_name), tempfile.TemporaryDirectory() as temp:
                directory = Path(temp) / 'copy'
                shutil.copytree(source, directory)
                target = directory / target_name
                with target.open(newline='', encoding='utf-8') as stream:
                    reader = csv.DictReader(stream)
                    fields, records = reader.fieldnames, list(reader)
                records[0][key] = str(int(records[0][key]) ^ 1)
                write_csv(target, fields, records)
                with self.assertRaises(ValueError):
                    verify_export(directory)

    def test_hand_specified_export_and_atomic_fault_rollback(self):
        for layout in ('linear', 'morton8'):
            for injection in ('none', 'gate', 'word'):
                with self.subTest(layout=layout, injection=injection), tempfile.TemporaryDirectory() as temp:
                    directory = Path(temp)
                    fixture(directory, layout=layout, injection=injection)
                    result = verify_export(directory)
                    self.assertEqual(result['candidate_verified'], injection == 'none')
                    self.assertEqual(result['rollback_verified'], injection != 'none')

    def test_mutations_fail_on_causal_state_geometry_search_and_bytes(self):
        def csv_change(path, key):
            with path.open(newline='', encoding='utf-8') as stream:
                reader = csv.DictReader(stream)
                fields, records = reader.fieldnames, list(reader)
            records[0][key] = str(int(records[0][key]) ^ 1)
            write_csv(path, fields, records)

        mutations = [('step_0/gate_trace.csv', 'parity'), ('step_0/branches.csv', 'admitted'),
            ('step_0/branches.csv', 'row'), ('step_0/words.csv', 'q_after'),
            ('step_0/words.csv', 'boundary_mask'), ('step_0/search.csv', 'path0'),
            ('committed_frontier.csv', 'id'), ('committed_words.csv', 'q')]
        for file, key in mutations:
            with self.subTest(file=file, key=key), tempfile.TemporaryDirectory() as temp:
                directory = Path(temp)
                fixture(directory)
                csv_change(directory / file, key)
                with self.assertRaises(ValueError):
                    verify_export(directory)
        for filename in ('candidate_tape.u32le', 'committed_tape.u32le'):
            with self.subTest(file=filename), tempfile.TemporaryDirectory() as temp:
                directory = Path(temp)
                fixture(directory)
                target = directory / filename
                data = bytearray(target.read_bytes())
                data[-1] ^= 128  # A padding bit, outside all logical tape cells.
                target.write_bytes(data)
                with self.assertRaises(ValueError):
                    verify_export(directory)

    def test_mutated_controller_output_or_memory_receipt_is_rejected(self):
        for field in ('phi_steps', 'decoded', 'device_payload_bytes'):
            with self.subTest(field=field), tempfile.TemporaryDirectory() as temp:
                directory = Path(temp)
                fixture(directory)
                target = directory / ('summary.json' if field == 'device_payload_bytes' else 'step_0/step.json')
                value = json.loads(target.read_text(encoding='utf-8'))
                if field == 'decoded':
                    value[field]['write'] ^= 1
                else:
                    value[field] += 1
                save_json(target, value)
                with self.assertRaises(ValueError):
                    verify_export(directory)

    def test_controller_write_causally_changes_exact_winding(self):
        program = read_program(ROOT / 'examples/universal/binary_increment.atomos')
        run = simulate_joint(program, nor_atlas(), budget=6, origin=-11, cells=37,
                             phi_base=64, max_frontier=128, j=1, k=1)
        self.assertEqual(run['stop'], 'halted')
        self.assertEqual([step['phi_steps'] for step in run['steps']], [64] * 5 + [128])
        self.assertEqual(run['state']['machine'], dict(control=1, head=5, tape={5: 1}))
        self.assertEqual(len(run['state']['frontier']), 64)
        self.assertEqual({leaf['row'] for leaf in run['state']['frontier']}, {7})
        self.assertEqual({leaf['angle'] for leaf in run['state']['frontier']}, {0})
        self.assertEqual(run['state']['q'], [0] * 16)

    def test_extinction_and_empty_frontier_do_not_halt_machine(self):
        program = read_program(ROOT / 'examples/universal/bounded_oscillator.atomos')
        for seed_live in (0, 1):
            run = simulate_joint(program, nor_atlas(), budget=4, origin=-1, cells=5,
                                 phi_base=1, max_frontier=4, j=1, k=1, seed_live=seed_live)
            self.assertEqual(run['stop'], 'running')
            self.assertEqual(len(run['steps']), 4)
            self.assertEqual(run['state']['frontier'], [])
            self.assertEqual(run['state']['words'], [0] * 16)
            self.assertEqual(run['state']['q'], [0] * 16)

    def test_resource_stop_retains_complete_prior_joint_prefix(self):
        program = read_program(ROOT / 'examples/universal/bounded_oscillator.atomos')
        run = simulate_joint(program, nor_atlas(), budget=4, origin=-1, cells=5,
                             phi_base=64, max_frontier=4, q_initial=1, j=1, k=1)
        self.assertEqual(run['stop'], 'frontier_cap')
        self.assertEqual(len(run['steps']), 2)
        self.assertEqual(len(run['evaluations']), 3)
        self.assertEqual(len(run['state']['frontier']), 4)
        self.assertEqual(run['state']['machine'], dict(control=0, head=0, tape={}))
        self.assertEqual(run['state']['q'], [1] * 16)

    def test_phi_overflow_and_tape_boundary_refuse_before_mutation(self):
        program = parse_program('atomos-universal 1\nstates 1\nalphabet 2\nstart 0 0\nrule 0 0 0 1 R\n')
        state = initial_joint(program, nor_atlas())
        decoded = table_output(program, 0, 0)
        for options, stop in ((dict(origin=0, cells=1, phi_base=1), 'tape_range'),
                              (dict(origin=0, cells=5, phi_base=(1 << 32) - 1), 'hinge_overflow')):
            result = causal_step(program, nor_atlas(), state, decoded,
                                 max_frontier=4, j=1, k=1, **options)
            self.assertEqual(result, dict(stop=stop, candidate=None))
            self.assertEqual(state['machine'], dict(control=0, head=0, tape={}))
            self.assertEqual(state['q'], [0] * 16)

    def test_zero_hinge_preserves_distinct_coincident_lineages(self):
        program = read_program(ROOT / 'examples/universal/bounded_oscillator.atomos')
        run = simulate_joint(program, nor_atlas(), budget=3, origin=-1, cells=5,
                             phi_base=0, max_frontier=8)
        self.assertEqual([leaf['id'] for leaf in run['state']['frontier']], list(range(8, 16)))
        self.assertEqual(sum(word.bit_count() for word in run['state']['words']), 1)
        self.assertTrue(all(child['diagnostic_status'] == 1 for step in run['steps'] for child in step['children']))

    def test_searches_include_absent_keys_and_complete_midpoint_paths(self):
        frontier = [dict(id=value, row=0, angle=0) for value in (2, 7, 9, 15, 32)]
        record = search_path(frontier, 7)
        self.assertEqual(record['found'], 1)
        self.assertEqual([record['path0'], record['path1']], [2, 1])
        self.assertEqual(record['visits'], 2)
        self.assertTrue(all(record[f'path{i}'] == (1 << 32) - 1 for i in range(2, 33)))
        for key in (0, 8, (1 << 64) - 1):
            self.assertEqual(search_path(frontier, key)['found'], (1 << 32) - 1)
        self.assertEqual(search_path([], 0)['visits'], 0)

    def test_word_fault_changes_admission_but_preserves_input_state(self):
        program = read_program(ROOT / 'examples/universal/bounded_oscillator.atomos')
        state = initial_joint(program, nor_atlas())
        result = causal_step(program, nor_atlas(), state, table_output(program, 0, 0),
            origin=-1, cells=5, phi_base=0, max_frontier=4, j=1, k=1, word_fault=True)
        self.assertEqual(result['candidate']['frontier'], [])
        self.assertEqual(result['candidate']['words'], [0] * 16)
        self.assertEqual(state['frontier'], [dict(id=1, row=0, angle=0)])
        self.assertEqual(state['words'][0], 1)

    def test_zero_budget_still_evaluates_initial_halt_and_does_not_step(self):
        program = parse_program('atomos-universal 1\nstates 1\nalphabet 1\nstart 0 0\nhalt 0\n')
        result = simulate_joint(program, nor_atlas(), budget=0, origin=0, cells=1,
                                phi_base=64, max_frontier=1)
        self.assertEqual(result['stop'], 'halted')
        self.assertEqual(len(result['evaluations']), 1)
        self.assertEqual(result['steps'], [])


if __name__ == '__main__':
    unittest.main()
