package org.atomos.radio;

import org.json.*;
import java.math.BigInteger;
import java.time.Instant;
import java.util.*;

/** Readable presentation of decoded evidence; never invents packet fields or application content. */
final class PacketPresentation {
    private PacketPresentation(){}
    static boolean layer(JSONObject packet,String protocol){JSONArray layers=packet.optJSONArray("protocols");if(layers!=null)for(int i=0;i<layers.length();i++)if(protocol.equalsIgnoreCase(layers.optString(i)))return true;return protocol.equalsIgnoreCase(packet.optString("protocol"));}
    static boolean matches(JSONObject packet,String filter,String query){if(!filter.equals("All") && !layer(packet,filter))return false;return query==null || query.trim().isEmpty() || packet.toString().toLowerCase(Locale.ROOT).contains(query.toLowerCase(Locale.ROOT).trim());}
    static String endpoint(JSONObject packet,String direction){String ip=packet.optString(direction+"_ip","unknown address");if(packet.has(direction+"_port"))return(ip.contains(":")?"["+ip+"]":ip)+":"+packet.optInt(direction+"_port");return ip;}
    static String title(JSONObject packet){JSONObject dns=packet.optJSONObject("dns");if(dns!=null){JSONArray questions=dns.optJSONArray("questions");String name=questions!=null && questions.length()>0?questions.optJSONObject(0).optString("name",""):"";return "DNS "+(dns.optBoolean("response")?"response":"query")+(name.isEmpty()?"":" · "+name);}JSONObject app=packet.optJSONObject("udp_application");if(app!=null)return app.optString("label",app.optString("protocol","UDP application metadata"));return layer(packet,"UDP")?"UDP datagram · application not decoded":packet.optString("protocol","Packet");}
    private static long checkedLong(BigInteger value){if(value.bitLength()>63)throw new ArithmeticException("Integer outside long range");return value.longValue();}
    static String timestamp(JSONObject packet){JSONObject time=packet.optJSONObject("timestamp");if(time==null)return"Capture time unavailable";String exact=time.optString("nanoseconds_exact","");if(!exact.isEmpty() && !exact.equals("null"))try{BigInteger[] parts=new BigInteger(exact).divideAndRemainder(BigInteger.valueOf(1000000000));if(parts[1].signum()<0){parts[0]=parts[0].subtract(BigInteger.ONE);parts[1]=parts[1].add(BigInteger.valueOf(1000000000));}return Instant.ofEpochSecond(checkedLong(parts[0]),checkedLong(parts[1])).toString();}catch(Exception ignored){}return "Exact capture timestamp: "+time.toString();}
    static String row(JSONObject packet){return "#"+packet.optInt("index")+"  "+title(packet)+"\n"+endpoint(packet,"source")+" → "+endpoint(packet,"destination")+"\n"+packet.optInt("captured_length")+" captured bytes · "+packet.optString("status");}
    static String detail(JSONObject p){StringBuilder out=new StringBuilder();out.append(title(p)).append("\n\n").append(endpoint(p,"source")).append("\n→ ").append(endpoint(p,"destination")).append("\n\n").append(timestamp(p)).append("\nCapture clock; no synchronization assumed.\n\n");
        out.append("Captured length: ").append(p.optInt("captured_length")).append(" bytes\nOriginal reported length: ").append(p.optInt("original_length")).append(" bytes\nDecode result: ").append(p.optString("status")).append('\n');
        if(p.optBoolean("capture_truncated"))out.append("The capture omitted bytes from this packet.\n");if(p.has("error"))out.append("Decoder detail: ").append(p.optString("error")).append('\n');
        if(layer(p,"UDP")){
            out.append("\nUDP\nDeclared datagram length: ").append(value(p,"udp_length")).append(" bytes (includes 8-byte header)\nDeclared payload: ").append(value(p,"udp_payload_declared_bytes")).append(" bytes\nCaptured payload: ").append(value(p,"udp_payload_captured_bytes")).append(" bytes\nPayload complete: ").append(value(p,"udp_payload_complete")).append("\nChecksum field: ").append(value(p,"udp_checksum_hex")).append(" (not verified)\n");
        }
        JSONObject dns=p.optJSONObject("dns");if(dns!=null){out.append("\nDNS ").append(dns.optBoolean("response")?"response":"query").append(" · transaction ").append(dns.optInt("id")).append("\nResponse code: ").append(dns.optInt("rcode")).append('\n');JSONArray questions=dns.optJSONArray("questions");if(questions!=null)for(int i=0;i<questions.length();i++){JSONObject q=questions.optJSONObject(i);if(q!=null)out.append("Question: ").append(q.optString("name")).append(" · ").append(dnsType(q.optInt("type"))).append('\n');}JSONArray records=dns.optJSONArray("records");if(records!=null)for(int i=0;i<records.length();i++){JSONObject r=records.optJSONObject(i);if(r!=null)out.append(r.optString("section","record")).append(": ").append(r.optString("name")).append(" · ").append(dnsType(r.optInt("type"))).append(" · ").append(r.has("address")?r.optString("address"):r.has("target_name")?r.optString("target_name"):"raw type retained").append(" · TTL ").append(r.optLong("ttl_seconds")).append(" s\n");}}
        if(p.optJSONObject("udp_application")!=null){out.append("\nApplication metadata\n");readable(p.optJSONObject("udp_application"),out,0);}
        if(layer(p,"UDP")){out.append("\nCaptured payload preview\n");if(p.has("udp_payload_text")){out.append(value(p,"udp_payload_preview_bytes")).append(" bytes shown; ").append(p.optBoolean("udp_payload_preview_truncated")?"preview limited":"entire captured payload fits").append(". Escaped ASCII represents original bytes, not decrypted content.\n\n").append(p.optString("udp_payload_text"));}else out.append("No payload preview in this stored report. Return and review the capture to refresh it.");}
        if(p.has("tls"))out.append("\n\nTLS record metadata only. Payload remains opaque; no stream reassembly or decryption.");return out.toString();}
    private static String value(JSONObject p,String key){return !p.has(key)||p.isNull(key)?"unavailable":String.valueOf(p.opt(key));}
    private static String dnsType(int type){switch(type){case 1:return"A (IPv4 address)";case 28:return"AAAA (IPv6 address)";case 5:return"CNAME (alias)";case 12:return"PTR (reverse/service name)";case 16:return"TXT";case 33:return"SRV";case 65:return"HTTPS";default:return"type "+type;}}
    private static String indent(int depth){return "                ".substring(0,Math.min(16,depth*2));}
    private static void readable(Object object,StringBuilder out,int depth){if(depth>4 || out.length()>100000)return;if(object instanceof JSONObject){JSONObject j=(JSONObject)object;Iterator<String> keys=j.keys();while(keys.hasNext()){String key=keys.next();Object v=j.opt(key);out.append(indent(depth)).append(key.replace('_',' ')).append(": ");if(v instanceof JSONObject || v instanceof JSONArray){out.append('\n');readable(v,out,depth+1);}else out.append(v).append('\n');}}else if(object instanceof JSONArray){JSONArray a=(JSONArray)object;for(int i=0;i<Math.min(64,a.length());i++)readable(a.opt(i),out,depth+1);}else out.append(indent(depth)).append(object).append('\n');}
    static String hex(JSONObject p){String raw=p.optString("udp_payload_hex","").replace(" ","");if(raw.isEmpty())return"No UDP payload hex preview available.";StringBuilder out=new StringBuilder("Raw captured UDP payload · hex bytes\n\n");for(int i=0;i<raw.length();i+=32){out.append(String.format(Locale.ROOT,"%04x  ",i/2));int end=Math.min(i+32,raw.length());for(int j=i;j<end;j+=2)out.append(raw,j,Math.min(j+2,end)).append(' ');out.append('\n');}if(p.optBoolean("udp_payload_preview_truncated"))out.append("\nPreview limited; original capture retains all captured bytes.");return out.toString();}
}
